#!/usr/bin/env python

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Copyright 2019, by the California Institute of Technology. ALL RIGHTS RESERVED.
# United States Government Sponsorship acknowledged. Any commercial use must be
# negotiated with the Office of Technology Transfer at the California Institute of
# Technology.  This software is subject to U.S. export control laws and regulations
# and has been classified as EAR99.  By accepting this software, the user agrees to
# comply with all applicable U.S. export laws and regulations.  User has the
# responsibility to obtain export licenses, or other export authority as may be
# required before exporting such information to foreign countries or providing
# access to foreign persons.
#
# Author: Yang Lei
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





import os
Import('envcontrib')
package = 'geo_autoRIFT'
envgeo_autoRIFT = envcontrib.Clone()
envgeo_autoRIFT['PACKAGE'] = envcontrib['PACKAGE'] + '/' + package
install = envcontrib['PRJ_SCONS_INSTALL'] + '/' + envgeo_autoRIFT['PACKAGE']
listFiles = ['__init__.py']
envgeo_autoRIFT.Install(install,listFiles)
envgeo_autoRIFT.Alias('install',install)
Export('envgeo_autoRIFT')

autorift='autoRIFT/SConscript'
SConscript(autorift)

geogrid='geogrid/SConscript'
SConscript(geogrid)
